### ISSUE TITLE
Fatal error:  Class 'FOS\UserBundle\Entity\User' not found with Symfony 3.*

### ISSUE THREAD

**Issue by cve** [chalasr/RCHJWTUserBundle#1]
Hi,

unfortunately when I want to use it with Symfony 3.* (fos-user-bundle must be at least in 2.0 version for support Symfony 3.* which I have in my composer.json) your bundle should have FOS\UserBundle\Model\User instead of FOS\UserBundle\Entity\User

**Comment by chalasr** [comment]
Hi @cve I'm looking for fixing this bug, it will be done today.

Thank you for use this and opening this issue. I keep you informed as soon as it is ok.

**Comment by cve** [comment]
If I reference "rch/jwt-user-bundle": "dev-fosuser_2.0" in my composer.json it works

**Comment by chalasr** [comment]
I'm facing an issue when installing the dependencies if fos-user ~2.0 is allowed, see https://travis-ci.org/chalasr/RCHJWTUserBundle/jobs/141439147. Glad to know that you can use it.

Sorry for the lack of documentation, If you have any need or problem, don't hesitate to open an issue so I quickly answer you and make changes when needed.

I'll try to fix the dependencies problem then provide a `2.x-dev` branch that you can require when using fosuser 2.0.

Thank you @cve

**Comment by chalasr** [comment]
@cve it should be fixed now. You can use this with friendsofsymfony/user-bundle 2.0 by requiring the `2.0.x-dev` branch of this bundle. If you encounter any problem, please let me know.
