### ISSUE TITLE
Any tutorial about how to use your bundle ?

### ISSUE THREAD

**Issue by AstonBraham** [chalasr/RCHJWTUserBundle#4]
Hello @chalasr 

Your bundle really seems awesome and usefull.
Is there a link to a tutorial about how to use it ?
If so please, let us know.

Cheers

**Comment by chalasr** [comment]
Hello @AstonBraham,

Thank you for using this and opening this issue.
Actually there is no documentation, I'll profit of your issue to write it as soon as possible.

Keep you informed here.

**Comment by AstonBraham** [comment]
That would be awesome...
I am currently reading through your codes to find a way to use it in
my current project...
Good job and Thanks for this

2016-07-12 16:34 UTC, Robin Chalas <notifications@github.com>:

**Comment by chalasr** [comment]
@AstonBraham, I'm working on right now, if you could wait tomorrow then you could stop trying to guess it (sorry for that).

**Comment by AstonBraham** [comment]
That would be awesome :D and It will sure help a lot of people...
Thanks Sir @chalasr !

2016-07-12 17:02 UTC, Robin Chalas <notifications@github.com>:

**Comment by chalasr** [comment]
@AstonBraham I just released the `v1.3.0` after adding documentation and fixed lots of stuff to make it stable (see [the README](https://github.com/chalasr/RCHJWTUserBundle#rchjwtuserbundle)).

You should now be able to use it. Please give me your feedback.
Thank you for having opened this issue!

If it's ok for you, then close it.

**Comment by AstonBraham** [comment]
That is really cool.. clear and really awesome..
Thanks for this,
I have even already implemented it in my android apps  backend for authentication..
Thanks sir :100:
